### ISSUE TITLE
Buttons do not work

### ISSUE THREAD

**Issue by impeeza** [Marice/ScreenTester-NX#1]
Hi I Am on Atmosphère 0.14.1 and Firmware 10.1.0 running Hekate 5.3.2 and the buttons doesn't work, only the [HOME] button which return to home OS, I already enable legacy IDMT on hekate and others old HomeBrew uses the buttons correctly.

Any help will be appreciated.

**Comment by Polraudio** [comment]
Any chance of fixing this?

**Comment by impeeza** [comment]
Nop, apears to be abbandoned, I did try to compile with the new DevKitPro, but serveral errors come, and the repair is beyond of my programming skills

**Comment by clamintus** [comment]
I fixed it here: #2

**Comment by Marice** [comment]
Sorry guys, did not have much time lately to keep this project updated. I merged clamintus his pull request with the fix so feel free to check that out. Will make a proper release of this new version soon. Thanks!

**Comment by impeeza** [comment]
Just compiled using MSys64 on Windows 11 and the result works, NRO doesn't have icon nor author information but works.

**Comment by Dr0bac** [comment]
Can someone share .nro file for us that doesn't know how to build homebrew from source?

**Comment by impeeza** [comment]
> Can someone share .nro file for us that doesn't know how to build homebrew from source?

It's Easy you can follow the guide https://gbatemp.net/threads/setup-a-devkitpro-environment-on-windows.652238/ on how to install a DevKitPro environment.

and then run the commands:

```
pacman --noconfirm -S git make devkit-env switch-sdl2_image switch-sdl2_mixer
git clone  --recursive https://github.com/Marice/ScreenTester-NX.git
cd ~/ScreenTester-NX
mkdir romfs
make -j

```

this is the result
[ScreenTester-NX.zip](https://github.com/user-attachments/files/18030380/ScreenTester-NX.zip)

**Comment by impeeza** [comment]
I am leaving a PR to add an Icon and improve the build process.

**Comment by Dr0bac** [comment]
Hey thanks for .nro file. Is that the latest version of screentester that you just pull requested?
If not, can you share that version also?
Thanks!!

**Comment by impeeza** [comment]
Nop, I made the PULL After build that one, this is the latest build including my PR

[ScreenTester-NX_2024_12_05-0.2-5-gf7446e1.zip](https://github.com/user-attachments/files/18031069/ScreenTester-NX_2024_12_05-0.2-5-gf7446e1.zip)
